### ISSUE TITLE
Invalid character in the given encoding

### ISSUE THREAD

**Issue by Fax3D** [FatturaElettronica/FatturaElettronica.Extensions#72]
Quando tento di leggere una fattura elettronica che contiene al suo interno, in una descrizione, il carattere **_°_** ottengo il seguente errore:

`System.Xml.XmlException: Invalid character in the given encoding. Line 128, position 49.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)
   at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.XmlReader.InternalReadContentAsString()
   at System.Xml.XmlReader.ReadContentAs(Type returnType, IXmlNamespaceResolver namespaceResolver)
   at System.Xml.XmlReader.ReadElementContentAs(Type returnType, IXmlNamespaceResolver namespaceResolver)
   at FatturaElettronica.Common.BaseClassSerializable.ReadXml(XmlReader r)
   at FatturaElettronica.Common.BaseClassSerializable.ReadXmlList(Object propertyValue, Type propertyType, String elementName, XmlReader r)
   at FatturaElettronica.Common.BaseClassSerializable.ReadXml(XmlReader r)
   at FatturaElettronica.Common.BaseClassSerializable.ReadXml(XmlReader r)
   at FatturaElettronica.Common.BaseClassSerializable.ReadXmlList(Object propertyValue, Type propertyType, String elementName, XmlReader r)
   at FatturaElettronica.Common.BaseClassSerializable.ReadXml(XmlReader r)
   at FatturaElettronica.FatturaBase.ReadXml(XmlReader r)
   at FatturaElettronica.Extensions.FatturaElettronicaXmlExtensions.ReadXml(FatturaBase fattura, String filePath)`

Per la lettura uso la funzione:

```
var _fattura = FatturaOrdinaria.CreateInstance(Instance.Privati);
_fattura.ReadXml(pFilePath);
```

La versione utilizzata è l'ultima disponibile, cioè la 2.0.1.

Grazie.

**Comment by nicolaiarocci** [comment]
Ciao, non riesco a riprodurre. Ho inserito quel carattere in un campo della fattura di test e la carico senza problemi.

**Comment by Fax3D** [comment]
Se vuoi posso fornirti il file originale così puoi testare direttamente quello... dove posso mandartelo?
Grazie.

**Comment by nicolaiarocci** [comment]
nicola at nicolaiarocci punto com
